name: Examen Deploy

on:
  workflow_dispatch: # Bot√≥n manual para ejecutar

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (Conectando a Backblaze)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APP_KEY }}
        run: terraform init

      - name: Terraform Apply (Desplegando en AWS Academy)
        env:
          # Credenciales B2 (Para guardar el estado)
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APP_KEY }}

          # Variables Lab 1
          TF_VAR_lab1_access_key: ${{ secrets.LAB1_ACCESS_KEY }}
          TF_VAR_lab1_secret_key: ${{ secrets.LAB1_SECRET_KEY }}
          TF_VAR_lab1_session_token: ${{ secrets.LAB1_SESSION_TOKEN }}
          TF_VAR_lab1_ami_id: ${{ secrets.LAB1_AMI_ID }}

          # Variables Lab 2
          TF_VAR_lab2_access_key: ${{ secrets.LAB2_ACCESS_KEY }}
          TF_VAR_lab2_secret_key: ${{ secrets.LAB2_SECRET_KEY }}
          TF_VAR_lab2_session_token: ${{ secrets.LAB2_SESSION_TOKEN }}
          TF_VAR_lab2_ami_id: ${{ secrets.LAB2_AMI_ID }}
        run: terraform apply -auto-approve